apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nexus-claroflex.clarobrasil.mobi/spring-maven:30
        ports:
        - containerPort: 8088
        env:
        - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
          value: "admin"
        - name: SPRING_DATA_MONGODB_USERNAME
          value: "root"
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: "flexDev"
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: "flexDev"  
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"     